@echo off
REM ========================================
REM Web-Based Chatbot - Project Runner
REM ========================================
REM This batch script builds and runs the chatbot application

cls
echo.
echo ╔════════════════════════════════════════════════════════════════╗
echo ║       Web-Based Chatbot - Spring Boot Application             ║
echo ╚════════════════════════════════════════════════════════════════╝
echo.

REM Get the project directory
set PROJECT_DIR=%~dp0
cd /d "%PROJECT_DIR%"

echo [INFO] Project Directory: %PROJECT_DIR%
echo.

if "%GEMINI_API_KEY%"=="" (
    echo [ERROR] GEMINI_API_KEY environment variable is not set.
    echo [HELP] Set it first, then rerun this script.
    echo [HELP] Example:
    echo        set GEMINI_API_KEY=your_actual_gemini_api_key
    pause
    exit /b 1
)

REM Step 1: Clean and Build
echo [BUILDING] Compiling project with Maven...
echo ----------------------------------------
call mvn clean compile package -DskipTests -q
if %errorlevel% neq 0 (
    echo [ERROR] Build failed! Please check your Maven installation.
    pause
    exit /b 1
)
echo [SUCCESS] Build completed successfully!
echo.

REM Step 2: Run the application
echo [RUNNING] Starting application on http://localhost:8085
echo ----------------------------------------
echo.
echo [INFO] Application started! Open your browser and navigate to:
echo        http://localhost:8085
echo.
echo [TEST] Ask any question in the chat UI. Responses are generated by Gemini.
echo.
echo [STOP] Press Ctrl+C to stop the application
echo ----------------------------------------
echo.

REM Run the JAR file
java -jar "%PROJECT_DIR%target\chatbot-1.0.0.jar"
pause
